version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: crm-2jmcmedios-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: TU_CLAVE    # <-- Debe coincidir con tu .env
      POSTGRES_DB: crm_2jmc
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
