version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: crm-2jmcmedios-prod-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-crm2jmc_root_2024}
      POSTGRES_DB: ${POSTGRES_DB:-crm_2jmc}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
      # CARGA EN ORDEN LÓGICO DE DEPENDENCIAS
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/01_init.sql
      - ./backend/db/insert_lugares.sql:/docker-entrypoint-initdb.d/02_insert_lugares.sql
      - ./backend/db/seed-admin.sql:/docker-entrypoint-initdb.d/03_seed-admin.sql
      - ./backend/db/insert_clientes.sql:/docker-entrypoint-initdb.d/04_insert_clientes.sql
      - ./backend/db/insert_emisoras.sql:/docker-entrypoint-initdb.d/05_insert_emisoras.sql
      - ./backend/db/insert_contc_emisora.sql:/docker-entrypoint-initdb.d/06_insert_contc_emisora.sql
      - ./backend/db/insert_contc_clientes.sql:/docker-entrypoint-initdb.d/07_insert_contc_clientes.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d crm_2jmc" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: crm-2jmcmedios-prod-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@crm2jmc.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin2024}
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data_prod:/var/lib/pgadmin
    depends_on:
      db:
        condition: service_healthy

  backend:
    image: crm-2jmcmedios-backend
    container_name: crm-2jmcmedios-prod-backend
    restart: always
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-crm2jmc_root_2024}@db:5432/${POSTGRES_DB:-crm_2jmc}
      PORT: 3001
      JWT_SECRET: ${JWT_SECRET:-SuperSecretKeyPara2jmcMediosCRM}
      NODE_ENV: production
    # No exponemos el 3001 al host por seguridad, Nginx se encarga de la comunicación interna
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: crm-2jmcmedios-frontend
    container_name: crm-2jmcmedios-prod-frontend
    restart: always
    # Se recomienda quitar los puertos si el túnel es la única forma de acceso
    ports:
      - "80:80"
    depends_on:
      - backend

  # Túnel Cloudflare (ID: 9eef95f1-1ce9-45a2-9dba-76777a60cbf0)
  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: crm-2jmcmedios-prod-tunnel
    restart: always
    command: tunnel --no-autoupdate --protocol http2 run --token eyJhIjoiMmM0ZTZhNWZkMzk5YjQ0NmM1NWI1NDI0ZTFlNDU0MTkiLCJ0IjoiOWVlZjk1ZjEtMWNlOS00NWEyLTlkYmEtNzY3NzdhNjBjYmYwIiwicyI6Ik1tSmxObVppTWpBdE5tWXpOQzAwT1dGbExXRmxOakV0TldKaU9ERXhZakEzTURndyJ9
    depends_on:
      - frontend

volumes:
  postgres_data_prod:
  pgadmin_data_prod:
