-- Script generado para insertar ciudades faltantes asociadas a sus Estados correspondientes

INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('Achaguas', 'Ciudad', 'Ciudad de Venezuela', 27);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('Aragua de Maturín', 'Ciudad', 'Ciudad de Venezuela', 32);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('Araure', 'Ciudad', 'Ciudad de Venezuela', 18);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('Araya', 'Ciudad', 'Ciudad de Venezuela', 31);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('Arismendi', 'Ciudad', 'Ciudad de Venezuela', 23);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('Bailadores', 'Ciudad', 'Ciudad de Venezuela', 24);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('Barbacoas', 'Ciudad', 'Ciudad de Venezuela', 13);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('Bejuma', 'Ciudad', 'Ciudad de Venezuela', 14);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('Bruzual', 'Ciudad', 'Ciudad de Venezuela', 27);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('Cabudare', 'Ciudad', 'Ciudad de Venezuela', 17);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('Cagua', 'Ciudad', 'Ciudad de Venezuela', 13);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('Caicara del Orinoco', 'Ciudad', 'Ciudad de Venezuela', 22);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('Camatagua', 'Ciudad', 'Ciudad de Venezuela', 13);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('Caripe', 'Ciudad', 'Ciudad de Venezuela', 32);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('Caripito', 'Ciudad', 'Ciudad de Venezuela', 32);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('Casanay', 'Ciudad', 'Ciudad de Venezuela', 31);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('Catia La Mar', 'Ciudad', 'Ciudad de Venezuela', 11);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('Chichiriviche', 'Ciudad', 'Ciudad de Venezuela', 16);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('Chivacoa', 'Ciudad', 'Ciudad de Venezuela', 19);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('Clarines', 'Ciudad', 'Ciudad de Venezuela', 29);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('Colón', 'Ciudad', 'Ciudad de Venezuela', 25);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('Colonia Tovar', 'Ciudad', 'Ciudad de Venezuela', 13);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('Cúpira', 'Ciudad', 'Ciudad de Venezuela', 12);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('Dabajuro', 'Ciudad', 'Ciudad de Venezuela', 16);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('El Callao', 'Ciudad', 'Ciudad de Venezuela', 22);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('El Consejo', 'Ciudad', 'Ciudad de Venezuela', 13);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('El Dorado', 'Ciudad', 'Ciudad de Venezuela', 22);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('El Limon', 'Ciudad', 'Ciudad de Venezuela', 13);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('El Socorro', 'Ciudad', 'Ciudad de Venezuela', 28);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('El Tocuyo', 'Ciudad', 'Ciudad de Venezuela', 17);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('Elorza', 'Ciudad', 'Ciudad de Venezuela', 27);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('Guacara', 'Ciudad', 'Ciudad de Venezuela', 14);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('Guama', 'Ciudad', 'Ciudad de Venezuela', 19);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('Guanta', 'Ciudad', 'Ciudad de Venezuela', 29);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('Guasdualito', 'Ciudad', 'Ciudad de Venezuela', 27);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('Guayabal', 'Ciudad', 'Ciudad de Venezuela', 28);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('Güigüe', 'Ciudad', 'Ciudad de Venezuela', 14);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('Juan Griego', 'Ciudad', 'Ciudad de Venezuela', 30);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('La Asunción', 'Ciudad', 'Ciudad de Venezuela', 30);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('La Esmeralda', 'Ciudad', 'Ciudad de Venezuela', 20);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('La Villa del Rosario', 'Ciudad', 'Ciudad de Venezuela', 33);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('Los Guayos', 'Ciudad', 'Ciudad de Venezuela', 14);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('Machiques', 'Ciudad', 'Ciudad de Venezuela', 33);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('Maiquetia', 'Ciudad', 'Ciudad de Venezuela', 11);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('Mamporal', 'Ciudad', 'Ciudad de Venezuela', 12);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('Mariara', 'Ciudad', 'Ciudad de Venezuela', 14);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('Marigüitar', 'Ciudad', 'Ciudad de Venezuela', 31);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('Michelena', 'Ciudad', 'Ciudad de Venezuela', 25);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('Morón', 'Ciudad', 'Ciudad de Venezuela', 14);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('Mucuchíes', 'Ciudad', 'Ciudad de Venezuela', 24);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('Naguanagua', 'Ciudad', 'Ciudad de Venezuela', 14);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('Ocumare de la Costa', 'Ciudad', 'Ciudad de Venezuela', 13);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('Onoto', 'Ciudad', 'Ciudad de Venezuela', 29);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('Ortiz', 'Ciudad', 'Ciudad de Venezuela', 28);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('Ospino', 'Ciudad', 'Ciudad de Venezuela', 18);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('Palmira', 'Ciudad', 'Ciudad de Venezuela', 25);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('Palo Negro', 'Ciudad', 'Ciudad de Venezuela', 13);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('Pampatar', 'Ciudad', 'Ciudad de Venezuela', 30);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('Pregonero', 'Ciudad', 'Ciudad de Venezuela', 25);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('Puerto Fermin', 'Ciudad', 'Ciudad de Venezuela', 30);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('Puerto Piritu', 'Ciudad', 'Ciudad de Venezuela', 29);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('Queniquea', 'Ciudad', 'Ciudad de Venezuela', 25);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('Quibor', 'Ciudad', 'Ciudad de Venezuela', 17);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('Río Caribe', 'Ciudad', 'Ciudad de Venezuela', 31);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('Río Chico', 'Ciudad', 'Ciudad de Venezuela', 12);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('Sabaneta', 'Ciudad', 'Ciudad de Venezuela', 23);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('San Antonio De Maturin', 'Ciudad', 'Ciudad de Venezuela', 32);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('San Antonio del Táchira', 'Ciudad', 'Ciudad de Venezuela', 25);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('San Carlos del Zulia', 'Ciudad', 'Ciudad de Venezuela', 33);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('San Casimiro', 'Ciudad', 'Ciudad de Venezuela', 13);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('San Diego', 'Ciudad', 'Ciudad de Venezuela', 14);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('San Francisco de Yare', 'Ciudad', 'Ciudad de Venezuela', 12);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('San Joaquín', 'Ciudad', 'Ciudad de Venezuela', 14);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('San Juan de Payara', 'Ciudad', 'Ciudad de Venezuela', 27);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('San Mateo', 'Ciudad', 'Ciudad de Venezuela', 13);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('San Rafael del Moján', 'Ciudad', 'Ciudad de Venezuela', 33);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('San Sebastian', 'Ciudad', 'Ciudad de Venezuela', 13);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('Sanare', 'Ciudad', 'Ciudad de Venezuela', 17);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('Santa Cruz', 'Ciudad', 'Ciudad de Venezuela', 13);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('Santa Elena de Uairén', 'Ciudad', 'Ciudad de Venezuela', 22);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('Santa Lucía', 'Ciudad', 'Ciudad de Venezuela', 12);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('Sarare', 'Ciudad', 'Ciudad de Venezuela', 17);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('Tinaco', 'Ciudad', 'Ciudad de Venezuela', 15);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('Tocuyito', 'Ciudad', 'Ciudad de Venezuela', 14);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('Turmero', 'Ciudad', 'Ciudad de Venezuela', 13);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('Villa de Cura', 'Ciudad', 'Ciudad de Venezuela', 13);
INSERT INTO LUGAR (nombre, tipo, descripcion, fk_lugar) VALUES ('Zaraza', 'Ciudad', 'Ciudad de Venezuela', 28);
